#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen royalboe' /etc/haproxy/haproxy.cfg
sed -i '/listen royaboe/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 29159-web-01 35.173.42.252:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 29159-web-01 35.173.42.252:80 check/a         server 652-web-02 44.211.23.142:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
