#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy
apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    daemon
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http
listen stats :1936
    stats enable
    stats hide-version
    stats realm loadbalanced\ Servers
    stats auth haproxy:haproxy
    stats uri /haproxy?stats
    
#stats uri /haproxy?stats
#    balance roundrobin
#    option httpclose
#    option forwardfor
#    server 375-web-01 35.173.42.252:80 check
#    server 375-web-02 44.211.23.142:80 check

frontend http-in
    bind *:80
    default_backend webservice

backend webservice
    balance roundrobin
    server 375-web-01 35.173.42.252:80 check
    server 375-web-02 44.211.23.142:80 check 
" >> /etc/haproxy/haproxy.cfg

service haproxy start
                      
