#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely handling SIGTERM 

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
