#!/usr/bin/env bash
# displays numbers from 1 to 100.

COUNTER=1
while [ $COUNTER -lt 101 ]
do
    if [ $((COUNTER%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNTER%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNTER%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    ((COUNTER+=1))
done
